//
// Created by ilnur on 16.03.2022.
//

#ifndef MASTER_CPP_DEFINES_H
#define MASTER_CPP_DEFINES_H

#define PORT 3459
#define CLOSE_CONNECTION_SYMBOL '#'
#define BUFF_SIZE 256
#define SERVER_IP "127.0.0.1"

#define RX_PACKET_SIZE 128
#define MAX_SLAVES_COUNT 10
#define QUEUE_SIZE 3
#define DEFAULT_COUNTER 0b11
#define RANDOM_COUNTER 0x1984
#define DEFAULT_ADDRESS 0x3FFF

#endif //MASTER_CPP_DEFINES_H
